---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_omnibus: false
  require_chef_for_busser: false
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  additional_copy_path: test/files
  #ansible_verbose: true
  #ansible_diff: true
  #ansible_verbosity: 2
  #idempotency_test: true
  #ansible_version:
  #custom_pre_install_command:	nil	Custom shell command to be used at beginning of install stage. Can be multiline.
  #custom_pre_play_command:	nil	Custom shell command to be used before the ansible play stage. Can be multiline. See examples below.
  #custom_post_install_command:	nil	Custom shell command to be used at after the install stage. Can be multiline.
  #custom_post_play_command:	nil	Custom shell command to be used after the ansible play stage. Can be multiline. See examples below.
  #env_vars:	Hash.new	Hash to set environment variable to use with ansible-playbook command
  #extra_vars: git c
  #extra_vars_file:	nil	file containing environment variables e.g. private_vars/production.yml site.yml Don't prefix with a @ sign.
  #group_vars_path:	group_vars	Ansible repo group_vars directory
  #host_vars_path:	host_vars	Ansible repo hosts directory
  #command: |

platforms:
  - name: ubuntu-1404
    driver_config:
      image: geerlingguy/docker-ubuntu1404-ansible:latest
      platform: ubuntu

suites:
  - name: default
  - name: python
