---
- name: make sure packages are installed
  apt: pkg={{item}} state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - libapache2-modsecurity
  notify: restart apache

- name: default apache site removed
  action: file path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: reload apache

- name: Apache | Enable some required modules
  apache2_module: name={{ item }} state=present
  with_items:
    - headers
    - remoteip
    - rewrite
    - ssl
  notify: reload apache
  tags:
    - common

- name: Apache | Enable Web Application Firewall
  apache2_module: name={{ item }} state=present
  with_items:
    - security2
  notify: reload apache
  tags:
    - web_application_firewall
    - CM-7
    - SC-7
    - SI-10

- name: Configure mod_remoteip
  template: src=templates/etc/apache2/conf-enabled/mod_remoteip.conf dest=/etc/apache2/conf-enabled/mod_remoteip.conf mode=0644
  notify: reload apache

- name: Disable /var/www
  template: >-
    src=templates/etc/apache2/conf-enabled/disable-var-www-indexes.conf
    dest=/etc/apache2/conf-enabled/disable-var-www-indexes.conf
    mode=0644
  when: apache2_disable_var_www_indexes
  notify: reload apache

- name: Apache ServerTokens Prod
  lineinfile:
    dest: /etc/apache2/conf-enabled/security.conf
    regexp: '^ServerTokens '
    line: 'ServerTokens Prod'
  notify: reload apache

- name: Apache ServerSignature Off
  lineinfile:
    dest: /etc/apache2/conf-enabled/security.conf
    regexp: '^ServerSignature '
    line: 'ServerSignature Off'
  notify: reload apache

- name: Configure TLS/SSL certificate
  lineinfile:
    dest: /etc/apache2/mods-enabled/ssl.conf
    regexp: '^SSLCertificateFile'
    line: SSLCertificateFile {{ apache2_ssl_certificate_file }}
  when: apache2_ssl_certificate_file is defined

- name: Configure TLS/SSL certificate key
  lineinfile:
    dest: /etc/apache2/mods-enabled/ssl.conf
    regexp: '^SSLCertificateKeyFile'
    line: SSLCertificateKeyFile {{ apache2_ssl_certificate_key_file }}
  when: apache2_ssl_certificate_key_file is defined

- name: Enable specific versions of SSL
  lineinfile:
    dest: /etc/apache2/mods-enabled/ssl.conf
    regexp: 'SSLProtocol '
    line: SSLProtocol {{ apache2_ssl_versions | join(' ') }}
  notify: reload apache

- name: Enable only strong SSL ciphers
  lineinfile:
    dest: /etc/apache2/mods-enabled/ssl.conf
    regexp: 'SSLCipherSuite '
    line: SSLCipherSuite {{ apache2_ssl_ciphers }}
  notify: reload apache

- name: ensure tmpfiles.d exists
  file: dest=/etc/tmpfiles.d mode=0755 owner=root group=root state=directory

- name: Create /var/run/apache2 with correct umask on startup
  copy: src=etc_tmpfiles_d_apache2.conf dest=/etc/tmpfiles.d/apache2.conf mode=0644 owner=root group=root

- name: enable apache2 mod_wsgi config to use custom python
  template: src=etc/apache2/conf-enabled/wsgi-custom-python.conf.j2 dest=/etc/apache2/conf-enabled/wsgi-custom-python.conf mode=0644
  notify: reload apache

- name: enable apache2
  service:
    name: apache2
    enabled: yes
