version: 2
jobs:
  test-kitchen:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run test-kitchen
          command: bundle exec kitchen test

workflows:
  version: 2
  commit:
    jobs:
    - test-kitchen
