---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/datagov-deploy-apache2
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - v1-venv-{{ checksum "requirements.txt" }}
            - v1-venv-
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v1-venv-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            make test

workflows:
  version: 2
  commit:
    jobs:
      - build
