---
- name: Converge
  hosts: all
  roles:
    - role: datagov-deploy-apache2
      # We use an existing prefix where python is
      # installed. Otherwise Apache/wsgi won't start up
      # properly.
      python_home: /usr
      apache2_enabled: false
  tasks:
    - name: create docroot
      file: dest=/www state=directory

    - name: copy custom index
      copy:
        content: |
          <h1>Hello World</h1>
        dest: /www/index.html
      notify: reload apache

    - name: copy custom site
      copy:
        content: |
          <VirtualHost 0.0.0.0:80>
            DocumentRoot /www
            <Directory /www>
              Require all granted
            </Directory>
          </VirtualHost>
        dest: /etc/apache2/sites-enabled/custom.conf
      notify: reload apache
